Budget App; Tennis Shop Argentina Capstone Final Rails
luccamicale/budget pull request #7
Opened 2023-02-24 12:58 UTC by luccamicale

Budget App; Tennis Shop Argentina 💯 

Capstone Final Rails 👍 

#https://github.com/luccamicale/budget

-Learning objectives
-Use ruby gems as software packages system.
-Install Ruby on Rails framework.
-Understand Rails RESTful design and router.
-Use controllers to handle requests and render empty views.
-Use params from browser request in a safe way.
-Use preprocessed html file with embedded Ruby code.
-Use layouts and templates for shared content.
-Use database migration files to maintain database schema.
-Use validations for models.
-Secure app from n+1 problems.
-Understand what ORM is.
-Write SQL queries with ActiveRecord.
-Set up associations between models.
-Build a webapp that requires the user to log in.
-Use devise gem for authentication.
-Limit access to webapp resources based on authorization rules.
-Analyze in writing why you have made a coding choice using one structure over another.

##Rspec work good!!!
![rspec-capstone](https://user-images.githubusercontent.com/107897361/221184298-ede4c817-bf1e-4cf9-9d26-be65d27b4103.png)

##Video 
https://www.loom.com/share/389cf270edae413fb660d0c968ccf72b

##Deploy;

2023-02-24 20:03 UTC, AnselemOdims requested changes
### Hi @luccamicale , 
You have been doing a tremendous job so far :ok_hand:
There are some issues that you still need to work on to go to the next project but you are almost there!

## To Highlight 🎉
PR has a title and summary. :heavy_check_mark:
No linter errors :heavy_check_mark:

## Required Changes ♻️
- [ ] Good job recording the video presentation, but please kindly include a piece of code you are proud of.
- [ ] Please also check inline comments under the review

## Optional suggestions
_Comments with the [OPTIONAL] prefix are not a must to implement however, It's strongly recommended to work on them as they can make your code better._

## Happy coding!👏👏👏

#### Please leave any questions or comments in the PR if you have any doubts or unclarity! You can tag me using @AnselemOdims for a quicker response

**_Note: Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-02-24 20:03 UTC, AnselemOdims commented on README.md
> +> Coming soon!.
- [ ] Please kindly add the link to the live project as it already been deployed.

2023-02-24 20:03 UTC, AnselemOdims commented on README.md
> +- COMING SOON
- [ ] Please kindly complete this section as you have already deployed the project

2023-02-24 20:03 UTC, AnselemOdims commented on app/views/home/index.html.erb
> +</section>
- [ ] Good job working on this page, but please kindly ensure that your design matches the original design.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/221275677-e59dfa90-5b74-494a-9794-50b463d511ca.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/221275496-6492901f-52db-4e86-a5c6-f33135cd36c5.png)

2023-02-24 20:03 UTC, AnselemOdims commented on app/views/devise/sessions/new.html.erb
> +</div>
- [ ] You did a good job building this page and working on the functionality but please kindly ensure that this page matches the original design. See below reference

### Your Design
![image](https://user-images.githubusercontent.com/43995830/221276440-14bad58f-a063-4f1b-b45e-5bfb4ef123b4.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/221276525-be157fbb-95d4-441f-b137-4cb01e36ec16.png)

2023-02-24 20:03 UTC, AnselemOdims commented on app/views/devise/registrations/new.html.erb
> +    <%= f.label :password_confirmation %><br />
- [ ] You did a good job building this page and working on the functionality but please kindly ensure that this page matches the original design. See below reference

### Your Design
![image](https://user-images.githubusercontent.com/43995830/221276898-51023572-f96e-40d2-b1c9-4001033b5578.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/221276712-c232365e-5a67-41e5-885e-4f609ed8f251.png)

2023-02-24 20:03 UTC, AnselemOdims commented on app/views/categories/index.html.erb
> +</div>
- [ ] Good job working on this page, but it does not follow the original design guidelines. Please kindly ensure it follows the original design guidelines.
- [ ] Also, all categories are supposed to be added to the categories index page.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/221278717-3a5d3e5a-7e3f-4076-be64-edfc8ee12b79.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/221278643-83633be5-bb66-4d5b-a621-ae39631041f6.png)

2023-02-24 20:03 UTC, AnselemOdims commented on app/views/payments/index.html.erb
> +</div>
- [ ] The payments page also does not follow the design and payments made do not appear accordingly.

### Your Design
![image](https://user-images.githubusercontent.com/43995830/221279311-1d51601b-4477-474f-a0b8-3bb4831b1c1f.png)

### Original Design
![image](https://user-images.githubusercontent.com/43995830/221275496-6492901f-52db-4e86-a5c6-f33135cd36c5.png)

2023-02-25 04:32 UTC, luccamicale commented
![det](https://user-images.githubusercontent.com/107897361/221338298-b4de2d7b-345f-4938-b1b8-3a9b305cdae1.png)
![paym](https://user-images.githubusercontent.com/107897361/221338301-7bf29f66-6f18-4ec4-be41-c9ebd611a801.png)
![categ](https://user-images.githubusercontent.com/107897361/221338302-023da592-55b6-494c-a01d-837d236975a5.png)
![LOG](https://user-images.githubusercontent.com/107897361/221338303-d04cb0f0-e2d9-4f1b-a585-04b9c0b74cbb.png)

2023-02-25 04:35 UTC, luccamicale commented
I follow the all requirement that he told me the last reviewer. I modified everypage in my project, the only problem was the design.
Now my project should be approved!!! 
👍 💯 🔢 🥇

2023-02-25 06:14 UTC, MeqdamAlqudah requested changes
Hi @luccamicale  

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![image](https://user-images.githubusercontent.com/74744787/221341929-3bd0ea61-0b2c-42c9-9877-c8bdcf3c52be.png)

 ## Highlights
:+1: no linter errors 
:+1: you done some changes good job for that

 ## Required Changes ♻️
_Check the comments under the review._

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-02-25 06:14 UTC, MeqdamAlqudah commented on README.md
- [ ] Good job by adding the link to the deployed project as the last reviewer said but it would be better to add it in its position in the Readme file as the last reviewer said.

2023-02-25 06:14 UTC, MeqdamAlqudah commented on README.md
- [ ] Please the last reviewer said here "ensure that your design matches the original design", I don't see that you made enough effort on this look how it looks, it doesn't match the design.
Your design 
![image](https://user-images.githubusercontent.com/74744787/221340606-8e61f7a1-68c7-43c8-8146-87126d755ddd.png)

The design 
![image](https://user-images.githubusercontent.com/74744787/221340633-4dcfb05e-a7bb-4857-90a9-4e53492920e8.png)

1 - there should be a header section on this page, also there should be a back button on it that let the user go to the root page as in the design, the background of this headline should be blue as in the design.
2 - forget password button should match the design

2023-02-25 06:14 UTC, MeqdamAlqudah commented on README.md
- [ ] Please as the last reviewer said this section should match the design, you did some changes to it but I don't think it is not enough 
![image](https://user-images.githubusercontent.com/74744787/221340939-d3a04b10-1b69-408b-8137-7d8451f7cdf4.png)
![image](https://user-images.githubusercontent.com/74744787/221340960-2324e58b-ac65-40ad-972b-4172aec14529.png)

- there should b a headline section that contains a back button to the root page, also the text on the top it is shouldn't sign up it says register as in the design.
- and since you will add the back button you don't  need these additional login button

2023-02-25 06:14 UTC, MeqdamAlqudah commented on README.md
> -- [Live Demo Link](https://yourdeployedapplicationlink.com)
- [ ] Please as the last reviewer said ensure your design follows the original design guidelines.
your design 
![image](https://user-images.githubusercontent.com/74744787/221341208-cb74c0dd-7132-4974-9892-75aab1b2b722.png)
Original design 
![image](https://user-images.githubusercontent.com/74744787/221341258-d1c221f9-2588-45d3-a3b8-5154b5c76458.png)

- the size of the category box doesn't match the design.
- the button add category should match the design it should have a green color and it should have a border as in the design
![image](https://user-images.githubusercontent.com/74744787/221341364-569609ca-5825-4692-b9d6-23688b5fa8af.png)
![image](https://user-images.githubusercontent.com/74744787/221341372-f8c592ca-f252-48aa-99c9-b35151c1f482.png)
- Please in the feature when you got your dream job nobody expects you to add something from your imagination to the design, they will require you to be strict, these buttons at the top don't match the design

2023-02-25 06:15 UTC, MeqdamAlqudah commented
> I follow the all requirement that he told me the last reviewer. I modified everypage in my project, the only problem was the design. Now my project should be approved!!! +1 100 1234 1st_place_medal

I'm sorry @luccamicale your project still need some work before the approval

2023-02-25 16:56 UTC, luccamicale commented
I modified again the styles about loing sign up categories annd payment. Now the pages looks very similar.
Please approved my project, I work wery hard in the styles with my maximun effort.

![catenew](https://user-images.githubusercontent.com/107897361/221369529-658c3385-1399-4e59-bf5f-4c191daf2d17.png)
![sign](https://user-images.githubusercontent.com/107897361/221369531-ec3b947d-78e4-4594-b2c5-35aa2f837a02.png)
![logiin](https://user-images.githubusercontent.com/107897361/221369534-1d980989-068d-407d-8e6a-a2a28f5cefb2.png)

2023-02-25 17:40 UTC, FrederickMih approved these changes
## Hi :raising_hand:  @luccamicale , 


In my opinion, your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

<img src="https://media.giphy.com/media/bdaMVCP6bPIVWc0B3g/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- PR is professional :+1: 
- Linter checks passed :heavy_check_mark: 

## Optional suggestions
**N/A**



Good luck! 🎉 


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

2023-02-25 17:53 UTC, merged